2025-03-16 10:08:46,667 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x715da8a5a690>: Failed to establish a new connection: [Errno 16] Device or resource busy')': /session
2025-03-16 10:08:46,677 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x715da8a61250>: Failed to establish a new connection: [Errno 16] Device or resource busy')': /session
2025-03-16 10:08:46,686 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x715da8a61e10>: Failed to establish a new connection: [Errno 16] Device or resource busy')': /session
